############################
# Fichier de congiguration #
############################

# General
site_title: Litho CMS
description: Litho est un CMS ultra-basique. Vous pouvez rédiger votre contenu en utilisant le langage Markdown.
keywords: CMS, KISS, Markdown
copyright: GNU GPL
author: Lahminewski
language: fr
default_page : index

# Theme (monolith, atom, lab)       
theme: monolith
layout: base

# Social networking and other links
  #pixelfed: 
  #mastodon: https://tooting.ch/@lahminewski
  #peertube:
  #matrix: 
  #wikimedia:
  #telegram: 
  #instagram:
  #discogs:
  #bandcamp: 
  github: https://github.com/Lahminewski/Litho
