############################
# Fichier de congiguration #
############################

# General
site_title: Devlopment de Litho CMS
description: 
keywords: CMS, 
copyright: CC-BY-SA
author: Lahminewski
language: fr
default_page : index

# Theme (monolith, atom, lab)       
theme: monolith
layout: base

# Social networking and other links
  #pixelfed: 
  #mastodon:
  #peertube:
  matrix: https://matrix.to/#/#Lahminewski-lab:matrix.org
  #wikimedia:
  #telegram:
  #instagram:
  #discogs:
  #bandcamp: 
  github: https://github.com/Lahminewski/Litho
